name: treefee_camera_and_editor
description: "A new Flutter module project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_editor_plus:
    path: packages/image_editor_plus
  pro_image_editor: ^2.7.3
  fluttertoast: ^8.2.5
#  file_picker: 5.2.10
  google_fonts: ^6.2.0
  go_router: ^14.0.2
  insta_assets_picker: ^2.3.0
  giffy_dialog: ^2.1.0
  uuid: ^3.0.7
  mime: ^1.0.4
  flutter_chat_types: ^3.6.2
  video_player: ^2.2.14
  video_trimmer: ^3.0.1
  file_picker: ^5.2.10
  # ffmpeg_kit_flutter: 6.0.3

  camerawesome:
    git:
      url: https://github.com/Apparence-io/CamerAwesome
      ref: a6715d98a8511a4c7fe736fbdd61ac97f53c231c

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  device_info_plus: 5.0.4

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.treefee_camera_and_editor
    iosBundleIdentifier: com.example.treefeeCameraAndEditor
