export enum ROUTES {
  STARTUP = "Startup",
  EXAMPLE = "Example",
  ONBOARDING = "Onboarding",
  LOGINSCREEN = "LoginScreen",
  OTPSCREEN = "OTPScreen",
  REGISTRATION = "Registration",
  TOPIC_SELECTION = "TopicSelection",
  PROFILE = "Profile",
  SEARCH = "Search",
  POST = "Post",
  TREE = "Tree",
  HOME = "Home",
  TABS = "TABS",
  VERIFY_PHONE_NUMBER = "VerifyPhoneNumber",
  SETTINGS_SCREEN = "SettingsScreen",
  LOCATION_MODAL = "LocationModal",
  CAMERA_PAGE = "CameraPage",
}
